CREATE USER tester WITH SUPERUSER PASSWORD 'user';
CREATE DATABASE tracker OWNER tester;
GRANT ALL PRIVILEGES ON DATABASE tracker TO tester;
CREATE DATABASE test OWNER tester;
GRANT ALL PRIVILEGES ON DATABASE test TO tester;