# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init-db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
      TRACKER_SCHEMA_FILE: tracker_schema.sql